---
title: "SUD Files"
---
 SUD Files  

SoundTrap data files
====================

### SUD Files

SoundTrap recorders from [Ocean Instruments](https://www.oceaninstruments.co.nz/) store data in proprietary files called SUD files. See SoundTrap documentation for information on how to extract SUD files from SoundTrap recorders.

Earlier versions of PAMGuard required you to 'inflate' the SUD files into standard wav audio files using the [SoundTrap Host software](https://www.oceaninstruments.co.nz/downloads/) before they could be processed.

The current version of PAMGuard no longer requires this since it can read data directly from the SUD files.

Inflating SUD files to WAV files generally required between 3 and 5 times as much disk space and could also take a fair amount of time, so not inflating will save both!

### SUD Index Files

To efficiently navigate SUD files, PAMGuard makes a map of each file and stores it in a new file in the same folder as the original SUD file. The index files have the same name as the original file, but end with .sudx. The index files are about 2.5% of the size of the original SUD files. When processing SUD files it is therefore important that a) the drive containing the SUD files is less than 95% full and b) that the system running PAMGuard has write access to the folder containing the SUD files.

### SUD File Times

The name of each SUD file contains the device serial number and a timestamp (data and time) in the form YYMMDDhhmmss. Note that these time stamps are in local time. When processing the file, PAMGuard will extract a UTC timestamp from within each SUD file and apply the UTC time to the data. you may therefore notice that the times of binary files and database entries differ from the times in the file names.

### Mixing SUD and WAV files

If a SUD file and a WAV file with the same name are in the same folder, then PAMGuard will ignore the SUD file and process the WAV file. Note that in this case, PAMGuard will be unable to extract any metadata from the SUD file and will not extract SoundTrap Click Detections (see below).

### SoundTrap Click Detector

If you are using the SoundTrap build in click detector (see SoundTrap manuals) then the SUD files will also contain detected clicks.

See the help page for the [SoundTrap Click Detector](../../../detectors/clickDetectorHelp/docs/SoundTrapClickDetector.html) for information on how to get these clicks from the SUD files into PAMGuard.
