---
title: "Running the System"
---
 Difar Module  

DIFAR Localisation
==================

Running the DIFAR System
------------------------

There are generally four main displays you need to interact with while processing DIFAR data:

1.  The [Spectrogram and Sidebar](./difar_UsingSpectrogram.html)
2.  The [DIFAR Queue](./difar_ManagingQueue.html)
3.  The [DIFAR Localisation](./difar_UsingDifarGramDisplay.html)

The software has been written to minimise the number of mouse clicks as far as is possible so that the operator can focus on validation of detections, and interpretation of localisations to facilitate real-time tracking. Getting a bearing to a sound should require no more than

1.  Marking that sound on the spectrogram with a click-and-drag of the mouse,
2.  Assigning a classification to each sound-clip in the [DIFAR queue](./difar_ManagingQueue.html) to [classify](./difar_ConfigureProcessing.html#Species) the sound for directional processing, and
3.  Verifying and saving the [DIFAR Localisation](./difar_UsingDifarGramDisplay.html) (by pressing the save button on the DIFAR display).

[Previous: Configure DIFAR Processing](difar_ConfigureProcessing.html)

[Next: Using the Spectrogram and Sidebar](difar_UsingSpectrogram.html)
