---
title: "References"
---
DIFAR Localisation
==================

References
----------

### DIFAR References (non-comprehensive list)

*   Blackwell SB, McDonald TL, Kim KH, Aerts LAM, Richardson WJ, Greene CRJ, Streever B (2012) Directionality of bowhead whale calls measured with multiple sensors. Mar Mammal Sci 28:200–212
*   Blackwell SB, Nations CS, McDonald TL, Greene CRJ, Thode AM, Guerra M, Macrander a. M (2013) Effects of airgun sounds on bowhead whale calling rates in the Alaskan Beaufort Sea. Mar Mammal Sci 29:E342–E365
*   Clark CW, Fowler M (2001) Status of archival and analysis effort of acoustic recordings during SOWER and IWC cruises 1996-2000. Rep Submitt to Sci Comm Int Whal Comm SC/53/IA28 \[Paper available from Off J Cetacean Res Manag
*   D’Spain G (1994) Relationship of underwater acoustic intensity measurements to beamforming. Can Acoust 2:157–158
*   Delagrange A (1992) DIFAR Multiplexer-Demultiplexer System, Latest Improvements. Silver Spring, Maryland
*   Ensor P, Komiya H, Beasley I, Fukutome K, Olson P, Tsuda Y (2007) 2006-2007 International Whaling Commission-Southern Ocean Whale and Ecosystem Research (IWC-SOWER) Cruise. Lyttelton, New Zealand
*   Ensor P, Komiya H, Olson P, Sekiguchi K, Stafford K (2006) 2005-2006 International Whaling Commission-Southern Ocean Whale and Ecosystem Research (IWC-SOWER) Cruise Report. Lyttelton, New Zealand
*   Ensor P, Minami K, Morse L, Olson P, Sekiguchi K (2008) 2007-2008 International Whaling Commission-Southern Ocean Whale and Ecosystem Acoustics Research (IWC-SOWER) Cruise. Lyttelton, New Zealand
*   Gedamke J, Robinson SM (2010) Acoustic survey for marine mammal occurrence and distribution off East Antarctica (30-80°E) in January-February 2006. Deep Sea Res Part II Top Stud Oceanogr 57:968–981
*   Greene CRJ, McLennan MW, Norman RG, McDonald TL, Jakubczak RS, Richardson WJ (2004) Directional frequency and recording ( DIFAR ) sensors in seafloor recorders to locate calling bowhead whales during their fall migration. J Acoust Soc Am 116:799–813
*   McDonald MA (2004) DIFAR hydrophone usage in whale research. Can Acoust 32:155–160
*   McDonald MA, Calambokidis J, Teranishi AM, Hildebrand JA (2001) The acoustic calls of blue whales off California with gender data. J Acoust Soc Am 109:1728
*   McDonald MA, Fox CG (1999) Passive acoustic methods applied to fin whale population density estimation. J Acoust Soc Am 105:2643–2651
*   McDonald MA, Hildebrand JA, Wiggins SM, Thiele D, Glasgow D, Moore SE (2005) Sei whale sounds recorded in the Antarctic. J Acoust Soc Am 118:3941–45
*   Miller BS, Barlow J, Calderan S, Collins K, Leaper R, Kelly N, Olson P, Ensor P, Double MC (2013) Long-range acoustic tracking of Antarctic blue whales. Rep Submitt to Sci Comm Int Whal Comm SC/65a/SH1:1–17
*   Miller BS, Collins K, Barlow J, Calderan S, Leaper R, McDonald M, Ensor P, Olson P a., Olavarria C, Double MC (2014) Blue whale vocalizations recorded around New Zealand: 1964–2013. J Acoust Soc Am 135:1616–1623
*   Oleson EM, Calambokidis J, Barlow J, Hildebrand JA (2007) Blue Whale Visual and Acoustic Encounter Rates in the Southern California Bight. Mar Mammal Sci 23:574–597
*   Oleson EM, Calambokidis J, Burgess WC, McDonald MA, LeDuc CA, Hildebrand JA (2007) Behavioral context of call production by eastern North Pacific blue whales. Mar Ecol Prog Ser 330:269–284
*   Peel D, Miller BS, Kelly N, Dawson SM, Slooten E, Double MC (2014) A simulation study of acoustic-assisted tracking of whales for mark-recapture surveys. PLoS One in press
*   Rankin S, Barlow J (2007) Vocalizations of the sei whale Balaenoptera borealis off the Hawaiian Islands. Bioacoustics Int J Anim Sound its Rec 16:137–145
*   Rankin S, Ljungblad DK, Clark CW, Kato H (2005) Vocalisations of Antarctic blue whales , Balaenoptera musculus intermedia , recorded during the 2001 / 2002 and 2002 / 2003 IWC / SOWER circumpolar cruises , Area V , Antarctica. J Cetacean Res Manag 7:13–20
*   Rivers J (1997) Blue whale, Balaenoptera musculus, vocalizations from the waters off central California. Mar Mammal Sci 13:186–195
*   Širovic A, Hildebrand JA (2011) Using passive acoustics to model blue whale habitat off the Western Antarctic Peninsula. Deep Sea Res Part II Top Stud Oceanogr 58:1719–1728
*   Swartz S, Cole T, McDonald MA, Hildebrand JA, Oleson EM, Martinez A, Clapham PJ, Barlow J, Jones M Lou (2003) Acoustic and visual survey of humpback whale (Megaptera novaeangliae) distribution in the eastern and southeastern Caribbean Sea. Caribb J Sci 39:195–208
*   Thode AM, D’Spain GL, Kuperman WA (2000) Matched-field processing, geoacoustic inversion, and source signature recovery of blue whale vocalizations. J Acoust Soc Am 107:1286–1300
*   Wade P, Heide-jørgensen MP, Shelden K, Barlow J, Carretta J, Durban J, Leduc R, Munger L, Rankin S, Sauter A, Stinchcomb C (2006) Acoustic detection and satellite-tracking leads to discovery of rare concentration of endangered North Pacific right whales Acoustic detection and satellite-tracking leads to discovery of rare concentration of endangered North Pacific right whales. Biol Lett 2:417–419
*   Wade P, Robertis a De, Hough K, Booth R, Kennedy a, LeDuc R, Munger L, Napp J, Shelden K, Rankin S, Vasquez O, Wilson C (2011) Rare detections of North Pacific right whales in the Gulf of Alaska, with observations of their potential prey. Endanger Species Res 13:99–109

[Previous: Difar Module Overview](difar_Overview.html)