---
title: "AIS Overview"
---
 AIS Overview  

AIS
===

Overview
--------

  

The Automatic Identification System (AIS) is a system used by ships and vessel management services to identify and locate ships. It is required on all commercial vessels of over 300 gross tons and all passenger vessels irrespective of size, although many other vessels also use it.

Vessels equipped with an AIS tranceiver system regularly transmit their position, speed, course, name, cargo and destination.

While AIS transceivers are expensive and must be registered with international shipping authorities, AIS receivers which do not transmit, but can receive data from other vessels can be purchased for a modest price.

PAMGUARD can decode AIS data and use it in a number of ways, for example:

1.  Display other vessels on the [PAMGuard map](../../../mapping/mapHelp/docs/overview.html)
    
2.  Display the locations of airguns on other vessels, which is particularly useful if PAMGUARD is being operated from a guard vessel or during multi-vessel surveys when airguns are in use on multiple vessels.
    

[](AISConfiguration.html)[Next: AIS Configuration](AISConfiguration.html)
