---
title: "Algorithms"
---
Group 3D Localiser
==================

Algorithms
----------

The Group 3D localiser has a number of available algorithms, the availability of which is dependent on both the layout of the array and the configuration of the detector used.

The [Crossed bearing](3dcrossedbearing.html) algorithm can be used when the detections already have bearing information. This may be because bearings have already been calculated by an internal algorithm within the detector, as is the case for the Click and Whistle and Moan detectors, or it may be a detection that has had bearing information added to it by the [Bearing Localiser](../../bearingLocaliser/docs/BL_Overview.html). This algorithm is also suitable for calculating positions from multiple [DIFAR buoys](../../difar/difarLocalisation/docs/difar_Overview.html).

The [Hyperbolic](3dhyperbolic.html) algorithm can be used to localise single detections from widely spaced hydrophones so long as Time Difference of Arrival measurements can be accurately made between the different hydrophone channels. Localisation can be in either 2 or 3 dimensions.

The [Simplex](3dsimplex.html) algorithm is an alternative to the [Hyperbolic](3dhyperbolic.html) algorithm, working with the same data, but solving the problem in a different way.

It is difficult to predict which algorithm will provide the best performance, both in terms of how many sounds it manages to localise and the spatial accuracy of those localisations. The [Crossed bearing](3dcrossedbearing.html) algorithm is a sensible choice if multiple compact clusters of hydrophones have been deployed, especially if there is some uncertainty as to the quality of time synchronisation between the clusters (they will need to be synchronised well enough to match sounds on the different clusters, but not so perfectly that Time Difference of Arrival measurements are reliable between clusters). If individual detections do not have bearing information (as would be the case for most wide aperture arrays), then the [Hyperbolic](3dhyperbolic.html) or the [Simplex](3dsimplex.html) algorithms should be used. Even if hydrophones are in clusters and bearing information is available, these algorithms should be more accurate due to their use of the additional time delays between distant hydrophones.

  

[Previous: Configuration](3dconfig.html)

[Next: Crossed bearing algorithm](3dcrossedbearing.html)