---
title: "Output"
---
 Group 3D Localiser  

Group 3D Localiser
==================

Localiser Output
----------------

The Group 3D localiser combines multiple detections from several hydrophones. When is successfully localises, it creates a new data object in PAMGuard which is in a new output stream, which is internally cross referenced back to the original detections.

#### Displays

Localiser output can be displayed on the [PAMGuard map](../../../mapping/mapHelp/docs/MapOverlays.html) by selecting the localiser from the maps drop down menu. Note that most detectors that can be used as input to the Group 3D localiser can also be displayed on the map, however the original detections will not have localisation information, so will either display at the location of the hydrophones they were detected on, or if they have bearings, show those bearing lines (with fixed range) from the hydrophone locations.

It is entirely up to you the user whether you display the original detections as well as the 3D localisations, or just one or the other.

#### Database

Successful localisations are written to the [PAMGuard database](../../../utilities/generalDatabaseHelp/docs/database_database.html).

The output table will use the name of the localiser, there being multiple tables if multiple localisers are in use. 3D information is provided in x,y,z format from the arrays main reference location and also as Latitude, Longitude and depth. There may be some variation as to exact column formats depending on choice of algorithm.
