---
title: "CHECKBOX Control"
---
 CHECKBOX Control  

CHECKBOX Control
================

The CHECKBOX Type is used to create a check box for entering true/false data on a Logger form

### Required Fields

**Order**

The order in which the controls are read in by the program

**Title**

The text to be shown on the display

### Optional Fields

**Autoclear**

The control is automatically cleared (deselected) when data is saved

**DbTitle**

Column heading for the output database. (This will default to the Title if this field is not completed)

**Hint**

Text for a hint to be displayed when entering data in the control

**PostTitle**

Additional text to display after the input box.

**Required**

Forces the user to fill in the input box before the form can be saved

**Plot**

If this is true (-1 in Access, generally any non zero or non null number) then data from this form can be plotted if the check box is selected. Note that there are extensive plot options available from the Display / Logger forms menu.

  
  

### NMEA Input

**NMEA\_Module**

The name of the NMEA module from which data should be harvested

**NMEA\_String**

The name of the NMEA string containing the data

**NMEA\_Position**

The position of the data item in the NMEA string. Strings are comma separated, the 0'the item will be the string name, the 1'st item the one after that, etc.

The checkbox will be set to true if the NMEA data is a non-null character of any type that is not "0".

  
  

[Back to form Design](./designingForms.html)