---
title: "LATLONG Control"
---
LATLONG Control
===============

The LATLONG Type is used on a User Defined Form to create an input field for Latitude and Longitude data

### Required Fields

**Order**

The order in which the controls are read in by the program

**Title**

The text to be shown on the display

**Length**

Length of the input field in characters

### Optional Fields

**Autoclear**

The control is automatically cleared when data is saved

**DbTitle**

Column heading for the output database. (This will default to the Title if this field is not completed)

**Hint**

Text for a hint to be displayed when entering data in the control

**PostTitle**

Additional text to display after the input box.

**Required**

Forces the user to fill in the input box before the form can be saved

  
  

### NMEA Input

**NMEA\_Module**

The name of the NMEA module from which data should be harvested

**NMEA\_String**

The name of the NMEA string containing the data

**NMEA\_Position**

The position of the first (Latitude) data item in the NMEA string. Strings are comma separated, the 0'the item will be the string name, the 1'st item the one after that, etc.

Two numbers will in face be read from the NMEA string. It is assumed that Latitude is at the position given by NMEA\_Position and that the next number in the NMEA string (i.e. NMEA\_Position+1) is the Longitude. Teh latitude and longitude should be in decimal degrees. If conversion of either number fails, the values will be set to null.

  
  

[Back to form Design](./designingForms.html)