---
title: "Using old Logger 2000 UDF forms"
---
Using old Logger 2000 UDF forms
===============================

Some users may wish to import UDF form definitions from databases used with the Logger 2000 software.

For compatibility with a wider range of database systems, we have had to make a number of changes to the format of the UDF\_tables in PAMGuad.

If you attempt to use an old Logger forms UDF table with PAMGuard you are likely to get a number of errors. To correct these, you will have to make the following changes to the UDF table. Please note that these changes may stop the table working with Logger 2000

1.  "Id" column: The PAMGuard forms must have a column titled Id of type AutoNumber, which should ideally also be set to be a primary key
2.  "Length" column has changed from Integer to Long Integer
3.  "NMEA String" column has changed to "NMEA\_String"
4.  "NMEA Position" column has changed to "NMEA\_Position and it's type has changed from Integer to Long Integer"
5.  "AutoUpdate" column has changed from Integer to Long Integer
6.  "ADC Channel" column has changed to "ADC\_Channel"
7.  "ADC Gain" column has changed to "ADC\_Gain"
8.  "Analog Multiply" column has changed to "Analog\_Multiply"
9.  "Analog Add" column has changed to "Analog\_Add"
10.  "Height" column has changed from Integer to Long Integer
11.  "Send Control Name" column has changed to "Send\_Control\_Name"
12.  "Control on Subform" column has changed to "Control\_on\_Subform"
13.  "Get Control Data" column has changed to "Get\_Control\_Data"

### Features not implemented

There are also several Logger 2000 features which have not yet been implemented in PAMGuard

1.  Button Forms
2.  Buttons on normal forms
3.  Sub forms
4.  Analogue input
5.  Form Colour
6.  Hotkeys (to open sub tab forms
7.  NOTOFFLINE, NOTONLINE and NOTSHOWDATA
8.  FONT

Subject to funding, we hope to add these features at some future date.