---
title: "SINGLE Control"
---
 SINGLE Control  

SINGLE Control
==============

The SINGLE Type is used on a User Defined Form to create an input field for single precision (32 bit) floating point data

### Required Fields

**Order**

The order in which the controls are read in by the program

**Title**

The text to be shown on the display

**Length**

Length of the input field in characters

### Optional Fields

**Autoclear**

The control is automatically cleared when data is saved

**DbTitle**

Column heading for the output database. (This will default to the Title if this filed is not completed)

**Hint**

Text for a hint to be displayed when entering data in the control

**PostTitle**

Additional text to display after the input box.

**Required**

Forces the user to fill in the input box before the form can be saved

**Plot**

Data from this form can be plotted if the entered value is non-zero. Note that there are extensive plot options available from the Display / Logger forms menu.

  
  

### NMEA Input

**NMEA\_Module**

The name of the NMEA module from which data should be harvested

**NMEA\_String**

The name of the NMEA string containing the data

**NMEA\_Position**

The position of the data item in the NMEA string. Strings are comma separated, the 0'the item will be the string name, the 1'st item the one after that, etc.

NMEA data will be converted to a single precision number. If the conversion fails, the control value will be set to null.

  
  

[Back to form Design](./designingForms.html)