---
title: "TIMESTAMP Control"
---
 TIMESTAMP Control  

TIMESTAMP Control
=================

The TIMESTAMP Type is used on a User Defined Form to create an input filed for date and time data

### Required Fields

**Order**

The order in which the controls are read in by the program

**Title**

The text to be shown on the display

**Length**

Length of the input field in characters

### Optional Fields

**Autoupdate**

This control will update on a time if a non-null positive integer value is entered in the Autoupdate column. The number is the number of seconds between auto-updates

**Topic**

The time zone for the data. By default all data are in UTC. Enter a standard time zone name to collect data in other time zones.

**Autoclear**

The control is automatically cleared when data is saved

**DbTitle**

Column heading for the output database. (This will default to the Title if this filed is not completed)

**Hint**

Text for a hint to be displayed when entering data in the control

**PostTitle**

Additional text to display after the input box.

**Required**

Forces the user to fill in the input box before the form can be saved

**Plot**

Data from this form can be plotted if the entered value is non-zero. Note that there are extensive plot options available from the Display / Logger forms menu.

  
  

### NMEA Input

**NMEA\_Module**

The name of the NMEA module from which data should be harvested

**NMEA\_String**

The name of the NMEA string containing the data

**NMEA\_Position**

The position of the data item in the NMEA string. Strings are comma separated, the 0'the item will be the string name, the 1'st item the one after that, etc.

It is assumed that the date and time are in adjacent positions in the NMEA string and that the NMEA\_Position is the position of the first Date field and the the Time is at NMEA\_Position+1. Currently it is also assumed that the date is in the form ddmmyy and that time is in the format hhmmss. We hope to support other date and time formats in future releases.

  
  

[Back to form Design](./designingForms.html)