---
title: "Overview"
---
Whistle Detector
================

Overview
--------

**

Note that the Whistle detector has now been replaced by the new  
[Whistle and Moan detector](../../whistleMoanHelp/docs/whistleMoan_Overview.html)  
and may be removed altogether from future PAMGuard releases

**

  
The Whistle detector finds odontocetes whistles by searching a spectrogram for 'ridges' of higher intensity sounds.

Whistle detection is a multi stage process:

### Background noise measurement and Peak detection

First a measure of background noise is made independently for each frequency in the spectrogram. The spectrogram data are then compared to the noise level and areas of the spectrogram that exceed the background noise level by the detection threshold are selected. For each time partition of spectrogram data, 'Peaks' are then generated by looking for adjacent frequency bins that are over threshold. Peaks are only generated if the number of adjacent frequency bins exceeding the threshold is between two specified limits to avoid noise spikes( when very few adjacent bins above threshold) and broad band sounds (when many adjacent bins above threshold). In addition, if a large percentage of all the frequency bins in a time partition are above threshold, no peaks are generated. (Again this is indicative of broad band sounds such as clicks).

### Linking

Detected peaks are then joined together. The joining process takes account of the frequency gradient, the rate of change of the frequency gradient and the rate of change of amplitude between peaks in successive time partitions and requires these to be values that are typical of odontocete whistles.

### Whistles

Once a time frequency contour is completed, it is classified as a whistle if it exceeds a minimum length. (In fact these are usually fractions of whistles.)

Future releases of PAMGuard will contain more sophisticated classification systems to determine species.

### Whistle Event

A Whistle Event occurs when the rate at which whistles are produces exceeds a specified minimum value. Since there is generally a low rate of false detection of individual whistles, and since encounters with most whistling species result in a high rate of whistle detection, whistle events are often a more useful indicator of the presence of animals than individual whistles.

### Whistle Localisation

If whistles are being detected on two or more pairs of hydrophones, then should whistles be detected simultaneously on multiple pairs (overlapping in time and frequency) the bearings from each hydrophone pair are automatically crossed to produce a location for the whistle source (subject to left-right ambiguity).

  

[Next: Creating a new whistle detector](whistleDetector_Creating.html)