---
title: "Workflow"
---
 SIDE Workflow  

SIDE Module
===========

Workflow
--------

There are two different workflows, depending on whether a Quick Test or a Random Drill is being run. Descriptions of each test can be found in the [Overview](SIDE_Overview.html#tests).

  

### Quick Test

The goal of a Quick Test is to determine the detection functionality of the PAM system in the current environmental conditions. The test is not intended to evaluate operator performance, but primarily to evaluate the efficacy of the automated detectors. Therefore, once started, the operator simply needs to wait until the Quick Test is complete. No further interaction is required.

Detection matching takes place in real time, with the SIDE module monitoring data coming from each detector and matching the simulated sounds with the detections. A match between an injected signal and detection is counted if there is overlap in time and frequency of the simulated sounds and the detection.

A summary report can be immediately generated for operator review once the Quick Test has completed.

  
  

### Random Drill

Random Drills are intended to test both operator alertness and automated detector efficiency over much longer periods of time and different noise conditions. Sequences are injected into the audio stream like the Quick Test, but at an infrequent rate (every few hours) over a period of days or even weeks.

The operator has three different methods to indicate that they have detected a sound.

1.  They can draw an annotation box around the signal in the spectrgoram
2.  They can hit the _Print Screen_ button in the top-left corner of the PAMGuard window
3.  They can click a _Things Heard_ button if they have an Aural Listening Form module loaded

In the case of an annotation box, a match between an injected signal and an operator detection is counted if there is an overlap in time and frequency of the simulated sound and the annotation box. For the _Print Screen_ and _Things Heard_ buttons, it is likely that the operator will have pressed the button at some time after the sound first becomes visible on the display. For these annotation types therefore, a match is considered good if the button was pressed within 30s of the sound reaching the hydrophones.

Automated detectors are evaluated the same as in the Quick Tests.

Over an extended period of time Random Drills will generate the same statistics as the quick tests, but are more likely to capture the full range of operational (noise) conditions and operator attentiveness.

  
  
  

[Previous: Sidebar](SIDE_Sidebar.html)

[Next: SIDE Output](SIDE_Output.html)