---
title: "Importing"
---
Quick Annotations
=================

Importing Quick Annotations
---------------------------

### Import

In Viewer Mode annotations can be imported into the QuickAnnotation module by selecting Import annotations from the file menu.

As of 2018-08-02 only CSV files of the following specific format can be imported, however this may change in the future.

### CSV format for importing QuickAnnotations

The file format for importing QuickAnnotations is headerless CSV with a comma for the field-delimiter and no quote character for strings.

One annotation should be listed per row, and each row should have seven columns (six commas). Fields marked with an asterisk (\*) are required and cannot be blank/null. The fields for each row should be:

**UTC, Channel, Duration, LowFreq, HighFreq, Label, Note**

**\*UTC** should be a number in the same format as java.lang.System.currentTimeMillis(), i.e. the difference, measured in milliseconds, between the current time and midnight, January 1, 1970 UTC(coordinated universal time).

**\*Channel** is the channel number for the annotation, and is **one-indexed**.

**\*Duration** is the duration, **in seconds**.

**\*LowFreq** and **HighFreq** are the lower and upper frequency bounds in Hz.

**Label** is a string (without commas) containing the user-designated label for the annotation.

**Note** is a string (without commas) containing the user-designated notes for the annotation.

[Previous: Annotations Configuration](adding.html)

[Next: Importing Annotations](import.html)
