---
title: "SoundTrap Click Detector"
---
Click Classification

Click Detector
==============

SoundTrap Click Detector
------------------------

If you are using a SountTrap recording device with built in click detection from [Ocean Instruments](https://www.oceaninstruments.co.nz/), you may need to use a modified version of the [Click Detector](ClickDetector_clickDetector.html).

The SoundTrap click detector allows you to detect and store clicks at high frequencies (say 384kS/sec), suitable for odontocete echolocation clicks, and at the same time, record audio data files at a lower frequency (e.g. 96 or 48kS/sec). This optimises disk space usage and makes long deployments of several months possible without running out of data storage.

Having two sample rates present within a single PAMGuard configuration is possible using [Decimator modules. However such configurations become particularly complicated to configure when the sample rate of the recorded files is lower than the sample rate of the click detector.](../../../sound_processing/decimatorHelp/docs/decimator_decimator.html)

[](../../../sound_processing/decimatorHelp/docs/decimator_decimator.html)

[We therefore recommend that you use a modified version of the](../../../sound_processing/decimatorHelp/docs/decimator_decimator.html) [Click Detector](ClickDetector_clickDetector.html), which manages it's own sample rate and channel information based on information extracted from the SoundTrap data.

Note that the SoundTrap click detector should only be used for clicks automatically detected by the SoundTrap. If you want to detect clicks from the SoundTrap recordings, then use a normal [Click Detector](ClickDetector_clickDetector.html) in the normal way.

### Creating an instance of the SoundTrap Click Detector

From the **_File>Add modules>Detectors_** menu, or from the pop-up menu on the data model display, select _'SoundTrap Click Detector'_ near the bottom of the Detectors list. Enter a descriptive name for the new detector and press Ok.

### Importing SoundTrap Data

SoundTrap data are stored in proprietary files called [SUD files](../../../sound_processing/AcquisitionHelp/docs/sudfiles.html).

There are two ways in which you can get data from [SUD files](../../../sound_processing/AcquisitionHelp/docs/sudfiles.html) into the SoundTrap Click Detector.

#### The Old Way

The 'standard' way of using SoundTrap data was to inflate all of the data from the compressed SUD files. For details of this process, see the SoundTrap user manuals and the SoundTrap Host software.

Normally, several inflated files are generated from each sud file:

1.  A wav file: Audio data in standard wav file format
2.  An XML file: Metadata on the SoundTrap configuration, file start times in various formats, etc.
3.  If the click detector was running BCL and DWV files, which contain the times of clicks and click waveforms respectively.

To convert the SUD files to the binary storage format used by PAMGuard, working in the [PAMGuard Viewer](../../../overview/PamMasterHelp/docs/viewerMode.html), create a Binary Store, a SoundTrap Click Detector and also create a 'SoundTrap Detector Import' module. Then use the import module to import the BCL and DWV data into PAMGuard. Once imported you can run [Click Classifiers](ClickDetector_clickClassification.html) and use other Click Detector offline functions to mark events, etc.

If you want to run additional analysis on the WAV file data (for example to [make noise measurements](../../../sound_processing/NoiseBands/Docs/NoiseBands.html) or to [detect whistles](../../whistleMoanHelp/docs/whistleMoan_Overview.html)), create a different PAMGuard configuration to process those data.

#### The (better) New Way

Current versions of PAMGuard can read [SUD files](../../../sound_processing/AcquisitionHelp/docs/sudfiles.html) directly, without first unpacking them into WAV, XML, BCL and DWV files. This not only reduces the amount of disk space you need by about x4, but also saves a lot of time.

Better still, you can now set up PAMGuard in normal mode to simultaneously process the audio data in the [SUD file](../../../sound_processing/AcquisitionHelp/docs/sudfiles.html) with one set of detectors, and simultaneously extract the click detector data into appropriate files for a SoundTrap Click Detector.

Start PAMGuard in [Normal Mode](../../../overview/PamMasterHelp/docs/normalMode.html) and add a [Sound Acquisition](../../../sound_processing/AcquisitionHelp/docs/AcquisitionOverview.html) module. Add a SoundTrap Click Detector, a [Binary Store](../../../utilities/BinaryStore/docs/binarystore_overview.html) store and a [Database](../../../utilities/generalDatabaseHelp/docs/database_database.html) module (optional). In the [Sound Acquisition dialog](../../../sound_processing/AcquisitionHelp/docs/AcquisitionConfiguration.html) select a single SUD file or a folder of SUD files. At this point, the SoundTrap Click Detector will be automatically configured with the correct sample rate (which won't be the sample rate displayed in the Sound Acquisition module).

Configure any [Click Classifiers](ClickDetector_clickClassification.html) you want to be run on the SoundTrap click data as it is imported.

You can then add any other detectors and measurement processes you want to run on the SoundTrap audio data, this may include instances of the normal Click Detector module if you want to detect clicks in the lower frequency audio data.

Process the data in the normal way and clicks will automatically be generated within the SoundTrap click detector

Further process you data using the [PAMGuard Viewer](../../../overview/PamMasterHelp/docs/viewerMode.html) in the normal way.