package rawDeepLearningClassifier.dlClassification.delphinID;

import org.jamdev.jdl4pam.transforms.SpectrumTransform;

import rawDeepLearningClassifier.dlClassification.delphinID.Whistles2Image.Whistle2ImageParams;
import rawDeepLearningClassifier.segmenter.SegmenterDetectionGroup;


