---
title: "Overview"
---
Analog Array Sensors
====================

Overview
--------

The Analog Array Sensors module can be used to measure the depth, pitch, roll and heading of a hydrophone array.

With simple line arrays, knowing the precise orientation of the array is probably not necessary. However as more users move towards using multi-channel, multi-dimensional hydrophone arrays in order to determine animal locations in three dimensions, knowing the orientation of array sections becomes increasingly important.

Three axis accelerometers are readily available at low cost. This module can be used with any sensors that have an analog voltage or current output. Analog devices have the advantage over digitital devices in that they don't introduce electrical noise into the hydrophone signals. If you are interested in digital accelerometers (e.g. in a fully digital array) then please contact the PAMGuard development team.

The system will allow for one set of sensors per hydrophone streamer. Depth and orientation data will be applied to all hydrophones within that streamer.

Two different types of data acquisition devices are currently supported:

*   MeasurementComputing data acquisition cards ([www.mccdaq.com](http://www.mccdaq.com)) which can connect to a PC or laptop via USB;
*   [Brain Boxes ED-549 devices](http://www.brainboxes.com/product/ed-549/ethernet-to-8-analogue-inputs-rs485-gateway) , which connect via Ethernet.

Depth, Heading, Picth and Roll information is passed to the [hydrophone array manager](../../../utilities/hydrophoneArrayManagerHelp/docs/Array_Overview.html) which makes it available to other PAMGuard modules as required.

#### Logging

If you are using the [PAMGuard Database](../../../utilities/generalDatabaseHelp/docs/database_database.html), changes to the streamer configuration will automatically be logged in the hydrophonestreamers database table.

  

[Next: Configuration](analogarrayconfig.html)