---
title: "Sound Output Overview"
---
Sound Output
============

Overview
--------

The sound output module can be used to play back sounds from PAMGuard through a sound card or other data acquisition device.

This allows you to aurally monitor sounds after they have been modified by PAMguard modules such as [Filters](../../FiltersHelp/Docs/filters_filters.html) or the [Seismic Veto](../../seismicveto/docs/veto_overview.html)

The availability of the sound output function depends on the type of input selected in the [Sound Acquisition](../../AcquisitionHelp/docs/AcquisitionOverview.html) module.

### Real time play back

When processing in real time, it is of course essential that sound output is at the same speed as the sound input. Ideally, you should select the same device for output as you are using for input to guarantee that they are running at exactly the same speed. Sometimes this is either impossible (because the input device doesn't have any outputs) or impractical for other reasons in which case you can use a different device but should be aware that there may be 'glitches' in the output.

If you're using the same device for output as for input, always use the same output sample rate. If using a different device, then you may need to use a different output sample rate, for example if your input data come from a high speed acquisition card sampling at 500kHz and you wish to play back through a sound card which can only output at 48kHz. In this case, PAMGuard will automatically decimate or up-sample the data so that the play-back is in real time. Of course, if you're acquiring high frequency data, you'll only be able to hear the part of that data that's in the audio band.

### File or PAMGuard Viewer play-back

If processing data from file, or using PAMGuard viewer, the speed at which data can play can be varied by the user via controls in the dialog or side panel.

Data will automatically be decimated or up-sampled to match the input sample rate, output sample rate of the device and the selected play speed.

### Creating sound output modules

From the _**F**_**_ile>Add modules>Sound Processing_** menu, or from the pop-up menu on the data model display select "**_Sound Output_**". Enter a name for the new module and press Ok.

Sound output modules can be inserted anywhere in the PAMGuard data model where there are raw audio data such as the output of a [Sound acquisition module](../../AcquisitionHelp/docs/AcquisitionOverview.html), a [Filter module](../../FiltersHelp/Docs/Filters_filters.html), a [Decimator](../../decimatorHelp/docs/decimator_decimator.html), a [Seismic Veto](../../seismicveto/docs/veto_overview.html), etc.

  
  

[Next: Sound Output Configuration](soundPlayback_Config.html)
