---
title: "Overview"
---
 Data Annotation  

Data Annotation
===============

Overview
--------

PAMGuard contains many different types of detector, most of which have their own unique set of output data which get stored either in the Binary Store or in the Database.

However, many types of data will have common measurements or manually entered comments associated with them. Since PAMGuard version 2.00.00 these have been organised into **Data Annotations**.

Annotations are built in as fixed parts of some PAMGuard modules. Within other modules, the user is presented with a list of data annotations they wish to select for the particular task they are configuring.

The selectable data annotations framework is only fully implements for the [Group Detection Localiser](../../../localisation/detectiongroup/docs/dglocaliser.html) but is likely to extend to other modules in the near future.

Modules employing the user selectable annotations framework may only offer a subset of the full list of annotations, depending on the compatibility of the annotation with the type of data generated by the module.

  

Annotation Data Storage
-----------------------

Most annotations are currently configured to save their data by adding additional columns to pre-existing database tables storing the output of particular modules in the [PAMGuard Database](../../../utilities/generalDatabaseHelp/docs/database_database.html). Future releases may also add annotation data to the [Binary data store.](../../../utilities/BinaryStore/docs/binarystore_overview.html)

Data Annotation Types
---------------------

### Sound Measurements

There are currently three annotation types which measure or act on sound data. These are:

1.  SNR Measurement. Measures Signal to Noise Ratio.
2.  SPL Measurement. Measures Sound Pressure Level.
3.  WAV File. Creates a WAV file clip.

These are only currently used built into larger modules

### User Input

There are two annotation types which invite the user to enter additional input to describe something they are observing on the PAMGuard Display. These are:

1.  [Text Annotations.](textannotation.html) Allows a simple line of text to be entered.
2.  [User Form Annotations.](loggerannotation.html) Allows the design and use of a more complex data entry form.

### Localisation

There is currently a single annotation type which adds localisation information to data. This is:

1.  [Target Motion Annotations.](targetmotionannotation.html) .