---
title: "Generic Localisers"
---
Localisation
============

Generic Localisers
------------------

  

The Generic Localisers are intended to work with any type of data from any PAMGuard detector. Some detectors, such as the Click Detector and the Whistle and Moan detector have built in bearing localisers and you should continue to use these. Most other detectors should use these generic localisers, and the 3D localiser can be used to estimate 2D and 3D locations for click and whistle data.

Some localisers will work on a single sound, detected on multiple hydrophones.

In general terms, there are three types of localisation that are possible for single sounds:  

1.  Bearings - a bearing in one or two dimensions (e.g. horizontal angle and elevation angle), possibly with ambiguity either side of the hydrophone array.
2.  2D Localisations - a Latitude and Longitude, or x,y position relative to the hydrophone array.
3.  3D Localisations - Latitude, Longitude, and depth or x,y,z, positions relative to the hydrophone array.

Another type of localisation, called [Target Motion Analysis](../targetmotion/docs/targetmotion_overview.html), uses the movement of the vessel and assumes that multiple sounds from the same source can be linked together, it then crosses multiple bearings to the sound source to generate a position. Target Motion Analysis can provide localisations using simpler arrays, but it's success is very dependent on animals producing regular vocalisations which can be linked together either automatically or by a human observer.

The type of localisation will depend a lot on the [type and layout of the array](localisation_arrays.html), its overall dimensions, the number of individual hydrophones, whether they are laid out in a line, a plane, or distributed in three dimensions. Success will also be heavily influenced by the types of sound being detected, their signal to noise ratio (it's easer if SNR is high!), the rate at which sounds are arriving (is it easy to match the different sounds on the different hydrophones, or are there many possibilities?), etc.

Often there are fundamental trade-offs of compromises to be made. For example, when localising harbour porpoise, you'll want to get the hydrophones quite far apart to cover the area or volume you're interested in, but at the same time you'll want the hydrophones quite close together or the highly directional sounds won't be detected on sufficient hydrophones for localisation. In most studies using wide aperture arrays, there will always be sounds detected on the periphery of the array which are only detected on one or two hydrophones and can't therefore be localised.

### Single Sound Localisers

#### Bearing Localiser

The [Bearing Localiser](../bearingLocaliser/docs/BL_Overview.html) is designed to work with compact arrays of two or more hydrophones. Implicit in it's operation is the assumption that hydrophones are close enough together that a sound detected on one hydrophone will also be present on others. Time delay measurements will be based on the cross correlation of the signals on the different channels and localisation will provide one or two bearings, depending on the type of array (linear, planar or volumetric).

Bearing localiser results are added as an annotation to the group detection and will be stored in both the database and in binary storage.

#### Group 3D Localiser

The [Group 3D Localiser](../group3d/docs/3doverview.html) has been developed for use with wide aperture arrays of four or more hydrophones. It links separate detections from multiple hydrophones and offers a choice of algorithms for 2 or 3 dimensional localisation

The automatic grouping of multiple detections to form a localisation generates a new data output stream in PAMGuard which is written to the database. Each database record contains information on which detections were used in the localisation and the localisation result.

### Multiple Sound Localisers

#### Target Motion Localiser

The [Target Motion Localiser](../targetmotion/docs/targetmotion_overview.html) can be used for 2D and 3D localisation using target motion analysis. It's input must be grouped detections, where the grouping has either been done automatically, e.g. using the Click Train Detector, or manually using the [Detection grouper](../detectiongroup/docs/dglocaliser.html). Detections within each group must have bearing information, e.g. from the [Bearing Localiser](../bearingLocaliser/docs/BL_Overview.html). For a linear array, the localisation will generally be ambiguous about the array axis, so two separate locations may be calculated, one for each side. For compact volumetrica arrays, which produce unambiguous bearings, the resulting localisation will also be unambiguous.

Target motion results are added as an annotation to the group detection and will be stored in both the database and in binary storage.

#### Detection grouper

The [Detection grouper](../detectiongroup/docs/dglocaliser.html) is not a localiser in itself, but can be used to manually group detections together on the PAMGuard displays for use with the [Target Motion Localiser](../targetmotion/docs/targetmotion_overview.html).

The detection grouper generates a new data output stream in PAMGuard which contains information on which detections were included in each group.

#### Example configurations

A selection of PAMGuard configuration files that illustate the use of some of the PAMGuard localisers with different detectors and types of array can be downloaded [here](http://www.pamguard.org/downloads.php?cat_id=3).

  
  

[Previous: Types of Array](localisation_arrays.html)

[Next: Time Difference of Arrival](localisation_tdoa.html)