package PamView;

public enum PamSymbolType {
	SYMBOL_CIRCLE, SYMBOL_CROSS,
	SYMBOL_CROSS2, SYMBOL_SQUARE, SYMBOL_TRIANGLEU, SYMBOL_DIAMOND, SYMBOL_POINT, SYMBOL_STAR,
	SYMBOL_TRIANGLED, SYMBOL_TRIANGLEL,SYMBOL_TRIANGLER, SYMBOL_PENTAGRAM,
	SYMBOL_HEXAGRAM, SYMBOL_CUSTOMPOLYGON, SYMBOL_DOUBLETRIANGLEL, SYMBOL_DOUBLETRIANGLER, SYMBOL_NONE, SYMBOL_LINESEGMENT
}
