---
title: "Mixed Mode operation"
---
 Mixed Mode Operation  

PAMGUARD
========

Mixed Mode Operation
--------------------

### Overview

PAMGUARD Mixed Mode is used to re-analyse data stored in audio files off-line.

When running in mixed mode, the PAMGUARD clock is set from the time in the name of the file and the current position within a file of audio data.

GPS data is read back from the database in synch with the PAMGUARD clock and sent into the PAMGUARD system exactly as though it was being collected in real time.

Any localisations calculated by PAMGUARD will therefore be based on the correct GPS data for the time at which the event occurred.

The overall look of PAMGUARD is also identical to that experienced during real time operation at sea.

New detections and localisations are written to the database. GPS data recycled through the system are not re-written to the database.

### Starting PAMGUARD Mixed mode operation

PAMGUARD Mixed mode can be started from the shortcut to PAMGUARD mixed mode placed on your system when you installed PAMGUARD.

If you are using one of the platform independent jar files, then run the jar file with the program argument -m. For instance, under Windows, the command line for starting PAMGUARD Beta version 1.3.02 in mixed mode with 1 Gigabyte of memory is:  
  

java -jar -mx1024m PamguardBeta\_1\_3\_02.jar Pamguard -m

### Running PAMGUARD Mixed Mode

When PAMGUARD starts in Mixed mode, it will not ask for a psf file, but will instead ask for a database file to open.

You must select a database which was previously filled with data from PAMGUARD.

As with [Viewer mode](viewerMode.html), PAMGUARD will read it's configuration settings from the database and not from a psf file.

Configure the [sound acquisition module](../../../sound_processing/AcquisitionHelp/docs/AcquisitionOverview.html) to take data either from a file or a file folder.

When you start PAMGUARD, there may be a pause of a few seconds as GPS and other data are extracted from the database.

Including a [sound output module](../../../sound_processing/soundPlaybackHelp/docs/soundPlayback_soundPlayback.html) in your model will enable you to hear the sounds and will also control the speed of analysis so that data are analysed in real time.

If you do not include a [sound output module](../../../sound_processing/soundPlaybackHelp/docs/soundPlayback_soundPlayback.html), data will be processed as fast as the machine is able. GPS data will however remain fully synchronised with the audio data.  
  

[Previous: PAMGUARD Viewer](viewerMode.html)

[Next: Graphical User Interface](guiOverview.html)
